# Generated by Django 4.1.2 on 2022-10-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='port_container',
            name='image',
            field=models.ImageField(default=1, upload_to='App/static/assets/img/'),
            preserve_default=False,
        ),
    ]
