# Generated by Django 4.1.2 on 2022-10-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_port_container_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Port_container',
        ),
    ]
